### PR TITLE
Use maturin to build release

### PR DESCRIPTION
**Pull request by gaborbernat**
Signed-off-by: Bernát Gábor <bgabor8@bloomberg.net>

### CODE REVIEW

**Comment by henryiii** [comment]
How did this compare? I came here to try musllinux_1_2, which I found out we support, but guess I'll have to look elsewhere to update https://github.com/pypa/cibuildwheel/pull/1816.

**Comment by gaborbernat** [comment]
From 12 minutes down to 3 with more wheel types https://github.com/tox-dev/pyproject-fmt-rust/actions/runs/9040915345

**Comment by henryiii** [comment]
You are building each in a separate job, not sure that's a perfectly fair comparison. cibuildwheel could be split up too, it can even generate the job matrix for you (with a little json wrangling). Maturin is downloading the manylinux docker too, so I expect it's pretty similar for similar jobs. Though I think you can disable the manylinux image with Maturin-action if you don't need it, which usually you don't, from what I gather.

Though those special archs will be _much_ slower in cibuildwheel, as it would use emulation instead of cross-compiling.

I just was testing musl, it seems like it works on 1_1, even if Rust was built with 1.2, you just can't do 32-bit without cross-compiling, which cibuildwheel can't do. Can the maturin action do musllinux? I don't see that in the output wheels.

**Comment by gaborbernat** [comment]
Oh, I am not saying it was fair, but was faster and quicker to set up, part of that was just that maturin generates the CI config for you. ` maturin generate-ci github`

**Comment by gaborbernat** [comment]
> Can the maturin action do musllinux? I don't see that in the output wheels.

I think is missing for now, though there's mention of it at https://www.maturin.rs/distribution

**Comment by henryiii** [comment]
It can, I've got both musllinux_1_2 wheels building now. Trying to see if I can get 1_1, though. (not that it likely matters here, but I want `uv` to support `1_1` so we can put it in manylinux, and this is a good learning project to try it in) :).

**Comment by gaborbernat** [comment]
Thanks!

**Pull request merged**
